version: '3'
services: 
    app:
        container_name: api
        restart: unless-stopped
        env_file: .env
        environment: 
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
            - MONGO_HOSTNAME=mongo
        build: .
        ports: 
            - "4000:4000"
        networks: 
            - app-net
        command: "./wait-for.sh mongo:27017 -- node ./dist/data/index.js"
        command: "npm run start"
    mongo:
        container_name: mongo
        image: mongo:4.2.6-bionic
        restart: unless-stopped
        volumes: 
            - "/home/victor/Escritorio/snk-db:/data/db"
        networks: 
            - app-net
networks: 
    app-net:
        driver: bridge